quasarframework/quasar-starter-kit

- README.md
> Fix vue-cli init not using @ for git template repo

- quasar-application/lib/quasar-config.js
> Create different dist file for mode and theme

- quasar-application/bin/qapp
> Rename info option to version

- quasar-application/bin/qapp-mode
> Enhance help message for qapp mode

- quasar-application/lib/quasar-config.js
> Fix publicPath merge order

- quasar-application/bin/qapp
- quasar-application/bin/qapp-build
- quasar-application/bin/qapp-dev
- quasar-application/bin/qapp-mode
- quasar-application/lib/cordova/index.js
- quasar-application/lib/helpers/ensure-argv.js
> Add options check and fix help

- quasar-application/bin/qapp-version
> closes #13: Show versions

- quasar-application/bin/qapp-version
> Add global vue-cli and cordova

- template/src/plugins/i18n.js
> Removed unused variable "store"

- template/quasar.conf.js
Default linting is not working if the project's folder name contains the word 'quasar'.
> ESLint ignore paths beginning with .

- template/package.json
0.19.0 resolved the problem but introduced a regression. This revision uses 0.18.1
Fix just the vuln without regressing
> feat(axios) proper vuln fix

- template/README.md
Improved the README template with app name, description, useful scripts and a reference to `quasar.conf.js` documentation. This change provides both a better looking and more useful **README** file than just `WIP` as the content. [Inspired](https://github.com/vuejs/vue-cli/issues/1675) from [Vue CLI](https://github.com/vuejs/vue-cli/blob/4af27247ccabe2ba5da57b6f216d17ad0767b8a8/packages/%40vue/cli/lib/util/generateReadme.js), adopted to Quasar with _slightly_ more content.
> feat: Improved README template

- template/src/css/quasar.variables.sass
- template/src/css/quasar.variables.scss
change "stylus" to "sass/scss" in corresponding files
> change "stylus" to "sass/scss" in corresponding files

- template/.gitignore
We don't need the dev files (www) or the core files which are copied across on each build (js/core)
> chore(bex): Add new BEX mode ignores.

- template/src/router/index.js
minor typo in 'router/index.js'
> fix(router): minor typo in 'router/index.js'

- template/.gitignore
- .gitignore changes
- No
Organized `.gitignore` template by dividing things into categories and commenting. Staying organized can help in the future for both maintainers and users.
> chore: organized .gitignore file

- template/.gitignore
- .gitignore improvements
- No
Related with https://github.com/quasarframework/quasar/issues/5728, it can be closed after merging this.
> chore: added ignores for Capacitor mode

- template/.eslintrc.js
> refactor: Refactored .eslintrc.js template

- template/.eslintrc.js
> chore: fixed the link in .eslintrc.js template

- template/quasar.conf.js
- Code style update
- No
This was slipped in with #80.
> style: Removed a trailing comma in quasar.conf.js template

- template/src/components/EssentialLink.vue
- template/src/layouts/MainLayout.vue
- template/src/router/routes.js
- Refactor
- No
Although extracting a component isn't necessary in this case, I thought providing an example of creating and using components would be a good idea, so I also extracted a component. I also renamed the layout file from `MyLayout` to `MainLayout` which is a better name to use any project IMO.
Partly inspired from #65.
> refactor: Refactored the Layout

- template/jsconfig.json
- template/quasar.conf.js
- template/src/components/EssentialLink.vue
- template/src/layouts/MainLayout.vue
- template/src/pages/Error404.vue
- template/src/pages/Index.vue
_**(default branch for this repo is `master`, @rstoenescu can you change the PR template)**_
If the user changes the linting rules of his app to stricter rules, some files provided by the starter kit are not complying. This PR keeps eslint happy, whatever rules the user has chosen
> chore(eslint): Keep eslint happy for all vue plugin rules

- meta.js
- template/src/components/OptionsComponent.vue
- template/src/pages/Index.vue
> fix(typescript): fix "Object API" typo

- template/tsconfig.json
Fixes https://github.com/quasarframework/quasar/issues/6856
> fix(typescript): set compilation target to ES5 if IE support is enabled, fix: #6856

- template/.eslintignore
WIP fixes for: https://github.com/quasarframework/quasar/issues/6883
> fix(bex): Ignore compilation output folder for linting (main repo: #6883)

- template/.eslintrc.js
> fix(linter): make vue rulesets valid when uncommented

- template/src/pages/Error404.vue
- template/src/pages/Index.vue
Vue.component() or Vue.extend() is needed when script lang="ts"
https://vuejs.org/v2/guide/typescript.html#Basic-Usage
This will close issue #6951 https://github.com/quasarframework/quasar/issues/6951
> Fix #6951 Index.vue and Error404.vue for Typescript projects

- template/src/pages/Error404.vue
> Fix change as to from

- template/.eslintignore
> fix(capacitor): avoid linting for generated files

- template/.eslintrc.js
> fix: prevent Prettier and ESLint argue over escaped quotes

- template/package.json
Sync with latest Composition API updates
https://github.com/vuejs/composition-api/releases
> chore(typescript): update deps

- template/.eslintrc.js
- template/package.json
- template/quasar.conf.js
- template/src/boot/axios.ts
- template/src/layouts/MainLayout.vue
> feat(lint-ts): upgrade @typescript-eslint dependencies

- template/quasar.conf.js
Some links were targeted to the old location.
- [x ] Bugfix
- [x ] No
> Updated links to documentation

- template/src/components/CompositionComponent.vue
Fixed Composition API example as proposed here: https://github.com/quasarframework/quasar/issues/4399#issuecomment-623035977
> fix(ts): fix composition-api example to avoid destructuring props

- template/src/router/index.ts
- template/src/store/index.ts
- template/src/store/module-example/actions.ts
- template/src/store/module-example/getters.ts
- template/src/store/module-example/index.ts
> fix(store): provide right type to "route" wrapper and rename StoreInterface, fix: #109

- template/src/App.vue
- template/src/components/EssentialLink.vue
- template/src/components/OptionsComponent.vue
- template/src/layouts/MainLayout.vue
- template/src/pages/Error404.vue
- template/src/pages/Index.vue
Only the example component had the chosen TS style and this let to some confusion to users (even if it showed all styles could be mixed).
This PR make all components comply with the chosen TS style.
Has been tested with all 3 styles and on plain JS projects.
> feat(ts): make all components comply with chosen TS style

- template/src/router/index.ts
> refactor: remove Vuex import when not used

- template/src/store/module-example/state.ts
> fix(Vuex+TS): return a fresh module state, avoid leaking state as global when using SSR

- meta.js
> refactor: update CSS preprocessors and ESLint preset options order to match community preference

- template/package.json
- template/quasar.conf.js
Same as https://github.com/quasarframework/quasar-starter-kit/pull/132
Backport the optimization into v1 branch
> refactor(linting): remove eslint-loader for TS projects

- template/.eslintignore
- template/.eslintrc.js
- template/package.json
- template/src/boot/i18n.ts
> feat: update deps

- template/src/store/index.ts
MUST BE MERGED AFTER https://github.com/quasarframework/quasar/pull/8712
> feat(ts): add Vuex typings

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- template/quasar.conf.js
> fix: fix minor issues in docs

- template/.eslintrc.js
> fix(linting): avoid "import/named" rule when using TS, fix #160

- .editorconfig
- .vscode/extensions.json
- .vscode/settings.json
- meta.js
- template/.vscode/extensions.json
- template/.vscode/settings.json
- template/README.md
- template/package.json
- template/quasar.conf.js
- utils/index.js
- Feature
- **[Vue Language Features (Volar) (johnsoncodehk.volar)](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar)**
- Moved [Vetur (octref.vetur)](https://marketplace.visualstudio.com/items?itemName=octref.vetur) from recommended to unwanted recommendations list.
- See: [IDE Support | SFC Tooling | Vue 3 Docs](https://v3.vuejs.org/api/sfc-tooling.html#ide-support)
- **[EditorConfig for VS Code (editorconfig.editorconfig)](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)**
- We were already providing `.editorconfig`, so I just added the related extension.
- …
> feat: Improve VS Code configuration & add a 'format' script for Prettier
